name: Análisis de Calidad

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Linter
        run: npm run lint

      - name: Validar tipos
        run: npx tsc --noEmit
